### PR TITLE
Add a vectorizer for word pieces

### PR DESCRIPTION
**Pull request by danieldk**
This is probably not the final API yet, but putting things in place to the point that we can start experimenting with feeding these to actual PyTorch models.

### CODE REVIEW

**Comment by DiveFish** [comment]
What are the prerequisites, i.e. programs that need to be installed for this to run? Currently, I am getting an `image not found` error when testing this (run locally, not on server).

**Comment by danieldk** [comment]
Do you have more information about what image is missing? I'd guess it's the PyTorch library (`libtorch`), but the `tch-rs` build script should download it. Maybe you are running into this issue?

https://github.com/LaurentMazare/tch-rs/issues/101

**Comment by danieldk** [comment]
The problem is that the upstream libtorch 1.2 libraries for macOS do not contain `libmklml`.

The libtorch 1.3.1 archive is complete library-wise. I have bumped the `tch-rs` dependency to a non-release version that support libtorch 1.31.

It's a bit worrying that we see even more basic deployment issues than with Tensorflow :(.

**Review by twuebi — APPROVED** [review]
looks good

> It's a bit worrying that we see even more basic deployment issues than with Tensorflow :(.

I certainly do not miss bazel. I guess we can see how this pans out and then decide whether to go for TF or torch. Model conversion from TF to torch works. Torch to TF should also be doable without major wizardry

**Review by DiveFish — APPROVED** [review]

**Pull request merged**
