### PR TITLE
Add encoder configuration and prepare utility

### PR DESCRIPTION
**Pull request by danieldk**
With this commit, it is possible to run `prepare` on a treebank and it
will output a file with the labels for each configured encoder.

The `finetune` utility is non-functional, but is added to verify that
deserialization of the labels also works.

### CODE REVIEW

**Comment by twuebi** [comment]
Is there an example config somewhere?

**Comment by danieldk** [comment]
Not yet, because other stuff will be added. Though I could add one as a unit test.

```toml
[labeler]
labels = "sticker.labels"
encoders = { pos = { sequence = "pos" }, dep = { dependency = "relativepos" } }
```

**Comment by danieldk** [comment]
> Not yet, because other stuff will be added. Though I could add one as a unit test.

I have added a unit test for the configuration format.

**Comment by twuebi** [comment]
Unrelated: getting `image not found` on macOS, this should not happen since the fix in #5?

Works on linux.

**Comment by danieldk** [comment]
> Unrelated: getting `image not found` on macOS, this should not happen since the fix in #5?
> 
> Works on linux.

Strange, this should be fixed indeed. Still works on my Mac, both inside and outside the Nix environment. What image is missing?

(There is now a new release, we could switch from the git version to the new release.)

**Comment by twuebi** [comment]
Trying the release

**Comment by twuebi** [comment]
> What image is missing?

libtorch.dylib

**Comment by twuebi** [comment]
Works if I manually download libtorch 1.31.

**Review by twuebi — APPROVED** [review]
I like and dislike the ron-serialization. It's convenient when you stay in rust, not that convenient if you want to do something outside of rust.  But I guess it's easy enough to write a small program to convert the labels to a line-based format. + it's not straight forward how to encode dependency labels / edit trees into a line-based format.

**Comment by danieldk** [comment]
> I like and dislike the ron-serialization. It's convenient when you stay in rust, not that convenient if you want to do something outside of rust. But I guess it's easy enough to write a small program to convert the labels to a line-based format. + it's not straight forward how to encode dependency labels / edit trees into a line-based format.

The usual formats have problems. I initially used JSON, which has the benefit of having nice tooling such as `jq`. But it cannot represent all the data types, so that failed with an error. TOML is much more limited. XML: meh. I can try if YAML can represent everything.

**Comment by danieldk** [comment]
> The usual formats have problems. I initially used JSON, which has the benefit of having nice tooling such as `jq`. But it cannot represent all the data types, so that failed with an error. TOML is much more limited. XML: meh. I can try if YAML can represent everything.

YAML seems to work. I will also add lemmas, to see if all bases are covered.

**Comment by danieldk** [comment]
Ok, now uses YAML for label storage and lemma edit trees are supported as well.

For the future: the serialization of `Numberer` is not ideal, since the mapping does not have to be serialized. I have a patch against `Numberer` that only serializes the labels once, but that breaks compatibility with older files, which is a problem for sticker 1. If we are happy with sticker 1 sticking with numberer 0.1.x and sticker-encoders 0.1.x, we could flip that switch. (It is possible to support both deserializations, but that would entail much more complexity.)

**Pull request merged**
