### PR TITLE
Add support for on-demand position embeddings

### PR DESCRIPTION
**Pull request by danieldk**
This is still a draft, because I'd like to ask your opinions on this approach. It would be nice to support positional embeddings that are generated on-demand (thus supporting sentences of an arbitrary length).

I had some generics-heavy abstractions over various embedding/configuration types. But thinking more about it, it may be simpler to just set things up such that when  `max_position_embeddings >= 1` position embeddings from the model are used, and on-demand positions otherwise.

Does that seem like a reasonable approach?

### CODE REVIEW

**Comment by twuebi** [comment]
`max_position_embeddings` is passed from the json file? Not too happy about the implicit meaning of 0 here. If it was a command-line argument, it could become an option here. Otherwise, I'm fine with this approach.

**Comment by danieldk** [comment]
> `max_position_embeddings` is passed from the json file? Not too happy about the implicit meaning of 0 here. If it was a command-line argument, it could become an option here. Otherwise, I'm fine with this approach.

Indeed, it's that option from the Bert JSON config. I guess another possibility would be to use the position embeddings when there is no `max_position_embeddings` in the JSON file. The the `BertConfig` struct could use an `Option` here.

**Comment by twuebi** [comment]
IMO making it dependent on the presence/absence of a key is still pretty implicit. If we go that route, I'd opt for a log message stating which type of pos-encoding is used. In case you're open to add a new entry to the json, I'd just add a field `position_encoding` with the two possible values `sinusoid` and `learned` ~with a comment above `max_position_embeddings` stating `"Only used with learned encoding"`~. Apparently, json doesn't support comments.

**Comment by danieldk** [comment]
I have updated the PR with a different approach. From the updated commit message:

---
This change adds the `position_embeddings` option to the `model`
section of the configuration. This option currently has one of two
possible values:
    
- `model`: use the position embeddings in the model parameter file.
- `sinusoidal`: use generated sinusoidal embeddings.
---

This is similar to your proposed solution, except that the option is in the main sticker configuration file, making it possible to enable this without changing the JSON file of the pretrain model. Plus, this option could be used for future supported models, without changing their model definitions as well.

**Review by twuebi — APPROVED** [review]

**Pull request merged**
